version: "3.9"
services:
  gimme:
    image: ziggornif/gimme:latest
    ports:
      - "8080:8080"
    volumes:
      - ./gimme.yml:/config/gimme.yml

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../../../monitoring/:/etc/prometheus/
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ../../../monitoring/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ../../../monitoring/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin